import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ActivityIndicator,
  TouchableOpacity,
  Alert,
  Share,
  Platform
} from 'react-native';
import { useAuth } from '../../contexts/AuthContext';
import { useLocalSearchParams, useRouter } from 'expo-router';
import axios from 'axios';
import { Ionicons } from '@expo/vector-icons';
import { LessonPlanDisplay } from '../../components/LessonPlanDisplay';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

const BACKEND_URL = process.env.EXPO_PUBLIC_BACKEND_URL;

export default function LessonDetail() {
  const { firebaseUser } = useAuth();
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const [lessonPlan, setLessonPlan] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (id) {
      loadLessonPlan();
    }
  }, [id]);

  const loadLessonPlan = async () => {
    try {
      setLoading(true);
      setError(null);
      if (firebaseUser) {
        const token = await firebaseUser.getIdToken();
        const response = await axios.get(`${BACKEND_URL}/api/lesson-plans/${id}`, {
          headers: { Authorization: `Bearer ${token}` }
        });

        if (response.data.success) {
          setLessonPlan(response.data.lessonPlan);
        }
      }
    } catch (err: any) {
      if (err.response?.status === 410) {
        setError('This lesson plan has expired and is no longer available.');
      } else if (err.response?.status === 404) {
        setError('Lesson plan not found.');
      } else {
        setError('Failed to load lesson plan. Please try again.');
      }
      console.error('Error loading lesson plan:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = () => {
    Alert.alert(
      'Delete Lesson Plan',
      'Are you sure you want to delete this lesson plan? This cannot be undone.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              if (firebaseUser) {
                const token = await firebaseUser.getIdToken();
                await axios.delete(`${BACKEND_URL}/api/lesson-plans/${id}`, {
                  headers: { Authorization: `Bearer ${token}` }
                });
                router.back();
              }
            } catch (err) {
              Alert.alert('Error', 'Failed to delete lesson plan.');
            }
          }
        }
      ]
    );
  };

  // Format lesson plan as shareable text
  const formatLessonPlanText = () => {
    if (!lessonPlan) return '';
    
    const plan = lessonPlan;
    let text = '';
    
    // Header
    text += `📚 LESSON PLAN\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━\n\n`;
    
    // Basic Info
    text += `📖 Subject: ${plan.subject || 'N/A'}\n`;
    text += `📊 Grade: ${plan.grade || 'N/A'}\n`;
    text += `🎯 Strand: ${plan.strand || 'N/A'}\n`;
    text += `📌 Sub-strand: ${plan.substrand || 'N/A'}\n`;
    text += `⏱️ Duration: ${plan.duration || 'N/A'} minutes\n`;
    text += `📅 Date: ${plan.createdAt ? new Date(plan.createdAt).toLocaleDateString() : 'N/A'}\n\n`;
    
    // Learning Outcome
    if (plan.slo) {
      text += `🎯 SPECIFIC LEARNING OUTCOME\n`;
      text += `${plan.slo}\n\n`;
    }
    
    // Introduction
    if (plan.introduction) {
      text += `📝 INTRODUCTION (${plan.introductionTime || '5'} min)\n`;
      text += `${plan.introduction}\n\n`;
    }
    
    // Development
    if (plan.development) {
      text += `📖 LESSON DEVELOPMENT (${plan.developmentTime || '25'} min)\n`;
      text += `${plan.development}\n\n`;
    }
    
    // Conclusion
    if (plan.conclusion) {
      text += `✅ CONCLUSION (${plan.conclusionTime || '5'} min)\n`;
      text += `${plan.conclusion}\n\n`;
    }
    
    // Assessment
    if (plan.assessment) {
      text += `📊 ASSESSMENT\n`;
      text += `${plan.assessment}\n\n`;
    }
    
    // Core Competencies
    if (plan.coreCompetencies && plan.coreCompetencies.length > 0) {
      text += `💡 CORE COMPETENCIES\n`;
      plan.coreCompetencies.forEach((c: string) => {
        text += `• ${c}\n`;
      });
      text += `\n`;
    }
    
    // Values
    if (plan.values && plan.values.length > 0) {
      text += `❤️ VALUES\n`;
      plan.values.forEach((v: string) => {
        text += `• ${v}\n`;
      });
      text += `\n`;
    }
    
    // Footer
    text += `━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `Generated by CBE Lesson Planner\n`;
    text += `Download the app: https://play.google.com/store/apps/details?id=com.legitlab.cbeplanner`;
    
    return text;
  };

  // State for PDF generation
  const [generatingPdf, setGeneratingPdf] = useState(false);

  // Share lesson plan as PDF
  const handleSharePdf = async () => {
    if (!id || !firebaseUser) return;
    
    try {
      setGeneratingPdf(true);
      
      // Get auth token
      const token = await firebaseUser.getIdToken();
      
      // Generate filename
      const subject = lessonPlan?.subjectName || 'Lesson';
      const grade = lessonPlan?.gradeName || 'Plan';
      const dateStr = new Date().toISOString().split('T')[0].replace(/-/g, '');
      const filename = `LessonPlan_${subject}_${grade}_${dateStr}.pdf`.replace(/\s+/g, '_');
      const fileUri = `${FileSystem.cacheDirectory}${filename}`;
      
      // Download PDF from backend
      const downloadResult = await FileSystem.downloadAsync(
        `${BACKEND_URL}/api/lesson-plans/${id}/pdf`,
        fileUri,
        {
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      );
      
      if (downloadResult.status !== 200) {
        throw new Error('Failed to generate PDF');
      }
      
      // Check if sharing is available
      const isAvailable = await Sharing.isAvailableAsync();
      
      if (isAvailable) {
        // Share the PDF file
        await Sharing.shareAsync(downloadResult.uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Share Lesson Plan PDF',
          UTI: 'com.adobe.pdf'
        });
      } else {
        // Fallback to text sharing if PDF sharing not available
        Alert.alert(
          'Sharing Unavailable',
          'PDF sharing is not available on this device. Would you like to share as text instead?',
          [
            { text: 'Cancel', style: 'cancel' },
            { text: 'Share as Text', onPress: handleShareText }
          ]
        );
      }
    } catch (error: any) {
      console.error('PDF share error:', error);
      Alert.alert(
        'Error',
        'Failed to generate PDF. Would you like to share as text instead?',
        [
          { text: 'Cancel', style: 'cancel' },
          { text: 'Share as Text', onPress: handleShareText }
        ]
      );
    } finally {
      setGeneratingPdf(false);
    }
  };

  // Share as text fallback
  const handleShareText = async () => {
    try {
      const content = formatLessonPlanText();
      
      await Share.share({
        message: content,
        title: `Lesson Plan - ${lessonPlan?.subjectName || 'CBE'}`
      });
    } catch (error: any) {
      Alert.alert('Error', 'Failed to share lesson plan');
      console.error('Share error:', error);
    }
  };

  if (loading) {
    return (
      <View style={styles.centerContainer}>
        <ActivityIndicator size="large" color="#6366F1" />
        <Text style={styles.loadingText}>Loading lesson plan...</Text>
      </View>
    );
  }

  if (error) {
    return (
      <View style={styles.centerContainer}>
        <Ionicons name="alert-circle-outline" size={64} color="#EF4444" />
        <Text style={styles.errorText}>{error}</Text>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <Text style={styles.backButtonText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (!lessonPlan) {
    return (
      <View style={styles.centerContainer}>
        <Text style={styles.errorText}>No lesson plan data.</Text>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <Text style={styles.backButtonText}>Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      {/* Expiration banner */}
      {lessonPlan.daysRemaining !== null && lessonPlan.daysRemaining !== undefined && (
        <View style={[
          styles.expirationBanner,
          { backgroundColor: lessonPlan.daysRemaining <= 1 ? '#FEF2F2' : '#F0FDF4' }
        ]}>
          <Ionicons
            name="time-outline"
            size={16}
            color={lessonPlan.daysRemaining <= 1 ? '#EF4444' : '#10B981'}
          />
          <Text style={[
            styles.expirationBannerText,
            { color: lessonPlan.daysRemaining <= 1 ? '#EF4444' : '#10B981' }
          ]}>
            {lessonPlan.daysRemaining === 0
              ? 'Expires today'
              : `Expires in ${lessonPlan.daysRemaining} day(s)`}
          </Text>
        </View>
      )}

      {/* Action buttons */}
      <View style={styles.actionBar}>
        <TouchableOpacity
          style={[styles.shareButton, generatingPdf && styles.shareButtonDisabled]}
          onPress={handleSharePdf}
          disabled={generatingPdf}
          data-testid="share-lesson-plan-pdf-btn"
        >
          {generatingPdf ? (
            <>
              <ActivityIndicator size={14} color="#6366F1" />
              <Text style={styles.shareButtonText}>Generating...</Text>
            </>
          ) : (
            <>
              <Ionicons name="document-text-outline" size={16} color="#6366F1" />
              <Text style={styles.shareButtonText}>Share PDF</Text>
            </>
          )}
        </TouchableOpacity>
        
        <TouchableOpacity
          style={styles.textShareButton}
          onPress={handleShareText}
          data-testid="share-lesson-plan-text-btn"
        >
          <Ionicons name="chatbubble-outline" size={16} color="#10B981" />
          <Text style={styles.textShareButtonText}>Text</Text>
        </TouchableOpacity>
        
        <TouchableOpacity
          style={styles.deleteButton}
          onPress={handleDelete}
          data-testid="delete-lesson-plan-btn"
        >
          <Ionicons name="trash-outline" size={16} color="#EF4444" />
          <Text style={styles.deleteButtonText}>Delete</Text>
        </TouchableOpacity>
      </View>

      {/* Lesson Plan Content */}
      <LessonPlanDisplay lessonPlan={lessonPlan} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF'
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#F9FAFB'
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#6B7280'
  },
  errorText: {
    fontSize: 16,
    color: '#374151',
    textAlign: 'center',
    marginTop: 16,
    marginBottom: 24
  },
  backButton: {
    backgroundColor: '#6366F1',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8
  },
  backButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600'
  },
  expirationBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    gap: 6
  },
  expirationBannerText: {
    fontSize: 13,
    fontWeight: '600'
  },
  actionBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
    gap: 24
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: '#EEF2FF',
    borderRadius: 16
  },
  shareButtonDisabled: {
    opacity: 0.7
  },
  shareButtonText: {
    fontSize: 13,
    color: '#6366F1',
    fontWeight: '500'
  },
  textShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F0FDF4',
    borderRadius: 16
  },
  textShareButtonText: {
    fontSize: 13,
    color: '#10B981',
    fontWeight: '500'
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 16,
    paddingVertical: 6
  },
  deleteButtonText: {
    fontSize: 13,
    color: '#EF4444',
    fontWeight: '500'
  }
});
